declare module 'react-native-linear-gradient'
// declare module 'expo-camera'
// declare module 'expo-device'
// declare module 'expo-location'
// declare module 'expo-secure-store'
// declare module 'react-native-maps'
